RS-1 microservico para tratamento de report com testes
ccem-dev/report-service pull request #1
Opened 2020-07-10 21:00 UTC by erickpoleto

2020-07-11 23:38 UTC, drferreira commented on README.md
> +--name outcomes-service outcomes-service`
Estas configuração são do outcomes não do reports.

2020-07-11 23:49 UTC, drferreira commented on source/app/controllers/ReportController.ts
> +      res.status(200).json({data: TemplateService.templateManager(report)})
Acredito que inverter a logica ficaria melhor pois durante o fluxo o caminho feliz fica visivel primeiro pois será o mais comum.
`if (!template.error){
      res.status(200).json({data: TemplateService.templateManager(report)})`
}else{
        return res.status(500).send({error: "template send error"})
}

2020-07-11 23:52 UTC, drferreira commented on source/app/factory/activityManager/ActivityManager.ts
> +}
Este microserviço é dedicado a reports e aqui temos conceitos de participante porque?

2020-07-11 23:53 UTC, drferreira commented on source/app/factory/report-factory/ReportFactory.ts
> +        //@ts-ignore
Remover.

2020-07-11 23:55 UTC, drferreira commented on source/app/routes/routes.ts
> +routes.post('/report', ReportController.getTemplate)
Este chamado rest retorna é o retorno do relatório? Se sim porque é um post?

2020-07-11 23:55 UTC, drferreira commented on source/config/app.ts
> +// import RouterInitializer from "../../app/routes/initializer";
remover.

2020-07-11 23:56 UTC, drferreira commented on source/package.json
> +  "name": "outcomes-service",
corrigir para reports-service

2020-07-11 23:56 UTC, drferreira commented on source/package.json
> +  "version": "1.2.0",
versão inicial deve ser 1.0.0

2020-07-11 23:57 UTC, drferreira commented on source/package.json
>      "typescript": "3.6.4"
Dependencias devem ter seu valor fixado, portanto deve ser removido ^

2020-07-11 23:58 UTC, drferreira commented on source/app/factory/activityManager/ActivityManager.ts
> +  }
Estes valores fixados aqui podem gerar problemas pois caso sejam alterados no api não será refletido aqui.

2020-07-11 23:58 UTC, drferreira commented on source/app/controllers/ReportController.ts
> +        return res.status(500).send({error: "template send error"})
Esta mensagem de retorno deve dizer mais do que erro.

2020-07-11 23:59 UTC, drferreira requested changes
Alguns itens anotados no código.

2020-07-12 00:13 UTC, erickpoleto commented on source/app/factory/activityManager/ActivityManager.ts
> +}
são funções utilizadas pelo script no report

2020-07-12 01:51 UTC, drferreira approved these changes

2020-07-12 01:51 UTC, merged